#WebApplicationType
spring.main.web-application-type=servlet

# Oracle DB 연결 설정
spring.datasource.url=jdbc:oracle:thin:@my-oracle-db.chcm40a2y81s.ap-northeast-2.rds.amazonaws.com:1521/ORCL
spring.datasource.username=admin  
spring.datasource.password=vmffhqj0124!
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA ÃÂ¬ÃÂÃÂ¤ÃÂ¬ÃÂ ÃÂ

spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

#ViewResolver Setting (JSPÃÂÃÂ­ÃÂÃÂÃÂÃÂÃÂÃÂ«ÃÂÃÂ©ÃÂÃÂ´ÃÂÃÂ¬ÃÂÃÂÃÂÃÂ ÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ­ÃÂÃÂÃÂÃÂ ÃÂÃÂ¬ÃÂÃÂÃÂÃÂ¤ÃÂÃÂ¬ÃÂÃÂ ÃÂÃÂ)
#spring.mvc.view.prefix=/WEB-INF/board/
#spring.mvc.view.suffix=.jsp

#Security Log Level
#logging.level.org.springframework.web=debug
#logging.level.org.springframework.sequrity=debug

# Thymeleaf View Resolver ÃÂ¬ÃÂÃÂ¤ÃÂ¬ÃÂ ÃÂ
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
#logging.level.org.thymeleaf=DEBUG

# JSP ÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂ ÃÂÃÂ ÃÂÃÂ¬ÃÂÃÂ¤ÃÂÃÂ ÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ«ÃÂÃÂ²ÃÂÃÂÃÂÃÂ«ÃÂÃÂ¥ÃÂÃÂ¼ restratÃÂÃÂ­ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂ§ÃÂÃÂ ÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ.
server.servlet.jsp.init-parameters.development=true

#Ã¬ÂÂ¤Ã­ÂÂÃ«Â§Â Ã«Â©ÂÃ¬ÂÂ¼Ã¬ÂÂ¤Ã¬Â Â
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dlawnsgh7476@gmail.com
spring.mail.password=emif acnx dbnu anld
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.servlet.session.timeout=30m

