#WebApplicationType
spring.main.web-application-type=servlet

# Oracle DB 연결 설정
spring.datasource.url=jdbc:oracle:thin:@my-oracle-db.chcm40a2y81s.ap-northeast-2.rds.amazonaws.com:1521/ORCL
spring.datasource.username=admin  
spring.datasource.password=vmffhqj0124!
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA 설정
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect


#ViewResolver Setting (JSPÃÂÃÂÃÂÃÂ­ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ«ÃÂÃÂÃÂÃÂ©ÃÂÃÂÃÂÃÂ´ÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ ÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ­ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ ÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¤ÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ ÃÂÃÂÃÂÃÂ)
#spring.mvc.view.prefix=/WEB-INF/board/
#spring.mvc.view.suffix=.jsp

#Security Log Level
#logging.level.org.springframework.web=debug
#logging.level.org.springframework.sequrity=debug

# Thymeleaf View Resolver ÃÂÃÂ¬ÃÂÃÂÃÂÃÂ¤ÃÂÃÂ¬ÃÂÃÂ ÃÂÃÂ
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
#logging.level.org.thymeleaf=DEBUG

# JSP ÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ ÃÂÃÂÃÂÃÂ ÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ¤ÃÂÃÂÃÂÃÂ ÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ«ÃÂÃÂÃÂÃÂ²ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ«ÃÂÃÂÃÂÃÂ¥ÃÂÃÂÃÂÃÂ¼ restratÃÂÃÂÃÂÃÂ­ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ§ÃÂÃÂÃÂÃÂ ÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ.
server.servlet.jsp.init-parameters.development=true

#ÃÂ¬ÃÂÃÂ¤ÃÂ­ÃÂÃÂÃÂ«ÃÂ§ÃÂ ÃÂ«ÃÂ©ÃÂÃÂ¬ÃÂÃÂ¼ÃÂ¬ÃÂÃÂ¤ÃÂ¬ÃÂ ÃÂ
# ë¤ì´ë² SMTP ì¤ì 
spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username=jangsh4752@naver.com
spring.mail.password=UGQGBKG5QM15
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.naver.com
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.from=jangsh4752@naver.com



#30ë¶ í ì¸ì ì¢ë£(ìë ë¡ê·¸ìì)
server.servlet.session.timeout=30m

